# Generated by Django 6.0.2 on 2026-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mchezo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="contribution_week",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Which week/period this contribution is for (1=first week, 2=second week, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="contribution",
            name="fine_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="contribution",
            name="is_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contribution",
            name="social_fund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="group",
            name="late_fine_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Standard fine for late contributions",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="social_fund_contribution",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Fixed amount for 'Mfuko wa Jamii' per period",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="bid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount bid (discount offered) to get this payout",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="net_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Actual amount received (Amount - Bid)",
                max_digits=15,
            ),
        ),
    ]
