# Generated by Django 6.0.2 on 2026-02-27 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wakala", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialday",
            name="closing_cash",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="financialday",
            name="closing_float",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="financialday",
            name="computed_closing_cash",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="financialday",
            name="computed_closing_float",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="financialday",
            name="opening_cash",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="financialday",
            name="opening_float",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
